### ISSUE TITLE
Required GPU Memory to run train_on_flyingthings3d.py

### ISSUE THREAD

**Issue by ipcoder** [tlkvstepan/PracticalDeepStereo_NIPS2018#1]
@tlkvstepan 

Hello, Stepan
I tried to run `train_on_flyingthings3d.py` script on 8GB GPU card and received: 
```
RuntimeError: CUDA out of memory. Tried to allocate 16.88 MiB (GPU 0; 8.00 GiB total capacity; 6.50 GiB already allocated; 125.04 MiB
free; 7.05 MiB cached)
```

Do you use larger GPU memory for this training?
Thank you.

**Comment by tlkvstepan** [comment]
Hi! 
Thank you for your interest. Training still requires quite a lot of memory since all intermediate results are saved for back propagation. I am using card with 12 GB GPU memory. Note that I am planing to share pre-trained models.
