### ISSUE TITLE
Is the current implementation able to reproduce the result in paper ?

### ISSUE THREAD

**Issue by chenchr** [tlkvstepan/PracticalDeepStereo_NIPS2018#2]
Hello. 
Thank you for the opensource of implementation. As therer is frequent commits, I am not sure whether the current implementation is able to reproduce the result ? 
Thanks !

**Comment by tlkvstepan** [comment]
Hello,
Please wait a bit, work is still in progress. I refactored the code and currently I am re-training the models to validate the performance.

**Comment by chenchr** [comment]
Thanks you for your jobs.

**Comment by tlkvstepan** [comment]
Pre-trained model for flyinthings3d is now available. It replicates results reported in the paper.
