### ISSUE TITLE
Do you intend to publish the trained networks?

### ISSUE THREAD

**Issue by ipcoder** [tlkvstepan/PracticalDeepStereo_NIPS2018#3]
Hi 
Are you still going to publish the networks trained on Flying Things and Kitti?

Thanks

**Comment by tlkvstepan** [comment]
Hello,
Pre-trained model for FlyingThings3D will be available in the end of this week. Fine-tuned KITTI model will be available later.

**Comment by tlkvstepan** [comment]
Pre-trained model for flyinthings3d is now available. It replicates results reported in the paper.
